project:
  type: website
  output-dir: docs

website:
  title: "STAT 1110: Fall 2026"
  favicon: "Images/Logos_Icons/hex.svg"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: "{{< fa house >}} Home"
  page-footer: "Site Designed by Dr. Ethan Marzban using <a href='https://quarto.org/' target='_blank'>Quarto</a>, ©2026 <br />"

format:
  html:
    theme: [minty, styles.scss]
    toc: true
